packages:
  - apps/*
  - libs/*
catalog:
  "@nestjs/common": ^11.0.0
  "@nestjs/core": ^11.0.0
  "@nestjs/platform-express": ^11.0.0
  "@nestjs/testing": ^11.0.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.0
  tslib: ^2.3.0
  "@sentry/nestjs": ^10.50.0
  cookie-parser: ^1.4.7
  dayjs: ^1.11.20
  dotenv: ^17.4.2
  morgan: ^1.10.1
  nestjs-i18n: ^10.7.5
  typeorm-transactional: ^0.5.0
  "@types/cookie-parser": ^1.4.10
  "@types/morgan": ^1.9.10
  mysql2: ^3.22.2
  "@nestjs/typeorm": ^11.0.1
  typeorm: ^0.3.28
  typeorm-naming-strategies: ^4.1.0
  joi: ^18.1.2
  "@nestjs/config": ^4.0.4
  "@nestjs/swagger": ^11.4.1
  ts-jenum: ^2.2.2
  class-transformer: ^0.5.1
  "@types/express": ^5.0.6
  decimal.js: ^10.6.0
  winston: ^3.19.0
  winston-daily-rotate-file: ^5.0.0
  "@slack/client": ^5.0.2
  class-validator: ^0.15.1
  "@lokalise/node-api": ^15.7.1
  adm-zip: ^0.5.17
  "@types/adm-zip": ^0.5.8
  concurrently: ^9.2.1
  nodemon: ^3.1.14
  "@logto/node": ^3.1.10
  "@nestjs/jwt": ^11.0.2
  jsonwebtoken: ^9.0.3
  "@types/jsonwebtoken": ^9.0.10
  neverthrow: ^8.2.0
  tsc-alias: ^1.8.16
  supertest: ^7.2.2
  "@types/supertest": ^7.2.0
  testcontainers: ^11.14.0
  "@testcontainers/mysql": ^11.14.0
  ts-jest: ^29.4.0
  tsx: ^4.21.0
  "@aws-sdk/client-ses": ^3.1045.0
  firebase-admin: ^13.9.0
  "@nestjs/schedule": ^6.0.1
  "@swc/helpers": ~0.5.18
allowBuilds:
  "@nestjs/core": false
  "@swc/core": false
  nx: false
  unrs-resolver: false
